package main

import (
	"io"
	"strings"
	"text/template"
)

func generate(w io.Writer, sumTypes []sumType) error {
	if len(sumTypes) == 0 {
		return nil
	}
	if err := fileHeaderTemplate.Execute(w, sumTypes[0].pkg); err != nil {
		return err
	}
	for _, st := range sumTypes {
		if err := generateSumType(w, st); err != nil {
			return err
		}
	}
	return nil
}

func generateSumType(w io.Writer, st sumType) error {
	type variantData struct {
		Name         string
		TypeParams   string
		MarkerMethod string
	}
	variants := make([]variantData, 0, len(st.variants))
	for _, v := range st.variants {
		tp := ""
		if len(v.typeParams) > 0 {
			tp = "[" + strings.Join(v.typeParams, ", ") + "]"
		}
		variants = append(variants, variantData{
			Name:         v.name,
			TypeParams:   tp,
			MarkerMethod: st.markerMethod,
		})
	}
	return sumTypeTemplate.Execute(w, variants)
}

var fileHeaderTemplate = template.Must(template.New("header").Parse(
	`// Code generated by go-sumtype. DO NOT EDIT.

package {{.}}

`))

var sumTypeTemplate = template.Must(template.New("sumtype").Parse(
	`{{range .}}func (*{{.Name}}{{.TypeParams}}) {{.MarkerMethod}}() {}
{{end}}
`))
