package main

import (
	"bytes"
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func mustGenerate(t *testing.T, sumTypes []sumType) string {
	t.Helper()
	var buf bytes.Buffer
	if err := generate(&buf, sumTypes); err != nil {
		t.Fatalf("generate: %v", err)
	}
	return buf.String()
}

var basicSumType = sumType{
	pkg:          "p",
	ifaceName:    "Shape",
	markerMethod: "isShape",
	variants: []variant{
		{name: "Circle"},
		{name: "Square"},
		{name: "Triangle"},
	},
}

var genericSumType = sumType{
	pkg:          "p",
	ifaceName:    "Wrapper",
	markerMethod: "isWrapper",
	variants: []variant{
		{name: "Box", typeParams: []string{"T"}},
		{name: "Pair", typeParams: []string{"K", "V"}},
		{name: "Plain"},
	},
}

func TestGenerate_nilProducesNoOutput(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	if err := generate(&buf, nil); err != nil {
		t.Fatalf("generate(nil): %v", err)
	}
	if buf.Len() != 0 {
		t.Errorf("expected empty output for nil, got %d bytes", buf.Len())
	}
}

func TestGenerate_emptySliceProducesNoOutput(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	if err := generate(&buf, []sumType{}); err != nil {
		t.Fatalf("generate([]): %v", err)
	}
	if buf.Len() != 0 {
		t.Errorf("expected empty output for empty slice, got %d bytes", buf.Len())
	}
}

func TestGenerate_outputIsValidGo(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "generated.go", src, 0); err != nil {
		t.Fatalf("generated code is not valid Go: %v\n\n%s", err, src)
	}
}

func TestGenerate_doNotEditHeader(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	if !strings.HasPrefix(src, "// Code generated by go-sumtype. DO NOT EDIT.") {
		t.Errorf("output should start with do-not-edit header; got:\n%s", src)
	}
}

func TestGenerate_packageDeclaration(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	if !strings.Contains(src, "package p") {
		t.Errorf("missing package declaration; got:\n%s", src)
	}
}

func TestGenerate_packageNameFromFirstSumType(t *testing.T) {
	t.Parallel()
	st := sumType{
		pkg: "mypkg", ifaceName: "X", markerMethod: "isX",
		variants: []variant{{name: "XFoo"}},
	}
	src := mustGenerate(t, []sumType{st})
	if !strings.Contains(src, "package mypkg") {
		t.Errorf("expected 'package mypkg'; got:\n%s", src)
	}
}

func TestGenerate_basicMethodStubs(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	for _, name := range []string{"Circle", "Square", "Triangle"} {
		want := "func (*" + name + ") isShape() {}"
		if !strings.Contains(src, want) {
			t.Errorf("missing %q in output:\n%s", want, src)
		}
	}
}

func TestGenerate_singleTypeParam(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{genericSumType})
	if !strings.Contains(src, "func (*Box[T]) isWrapper() {}") {
		t.Errorf("missing generic stub for Box[T]; got:\n%s", src)
	}
}

func TestGenerate_multipleTypeParams(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{genericSumType})
	if !strings.Contains(src, "func (*Pair[K, V]) isWrapper() {}") {
		t.Errorf("missing generic stub for Pair[K, V]; got:\n%s", src)
	}
}

func TestGenerate_variantWithNoTypeParams(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{genericSumType})
	// Plain has no type params; receiver must not have brackets.
	if !strings.Contains(src, "func (*Plain) isWrapper() {}") {
		t.Errorf("missing plain stub; got:\n%s", src)
	}
}

func TestGenerate_multipleSumTypesInOneFile(t *testing.T) {
	t.Parallel()
	st2 := sumType{
		pkg: "p", ifaceName: "Color", markerMethod: "isColor",
		variants: []variant{{name: "Red"}, {name: "Blue"}},
	}
	src := mustGenerate(t, []sumType{basicSumType, st2})

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "generated.go", src, 0); err != nil {
		t.Fatalf("multiple sumtypes generated invalid Go: %v\n\n%s", err, src)
	}
	for _, want := range []string{
		"func (*Circle) isShape() {}",
		"func (*Square) isShape() {}",
		"func (*Red) isColor() {}",
		"func (*Blue) isColor() {}",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing %q; got:\n%s", want, src)
		}
	}
}

func TestGenerate_stubsAppearOnce(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	if count := strings.Count(src, "func (*Circle) isShape() {}"); count != 1 {
		t.Errorf("Circle stub appeared %d times, want 1", count)
	}
}

func TestGenerate_variantsPreserveOrder(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{basicSumType})
	circlePos := strings.Index(src, "Circle")
	squarePos := strings.Index(src, "Square")
	trianglePos := strings.Index(src, "Triangle")
	if circlePos > squarePos || squarePos > trianglePos {
		t.Errorf("variant stubs not in declaration order; got:\n%s", src)
	}
}

func TestGenerate_genericOutputIsValidGo(t *testing.T) {
	t.Parallel()
	src := mustGenerate(t, []sumType{genericSumType})
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "generated.go", src, 0); err != nil {
		t.Fatalf("generic sumtype generated invalid Go: %v\n\n%s", err, src)
	}
}

func TestGenerate_singleVariant(t *testing.T) {
	t.Parallel()
	st := sumType{
		pkg: "p", ifaceName: "Singleton", markerMethod: "isSingleton",
		variants: []variant{{name: "Only"}},
	}
	src := mustGenerate(t, []sumType{st})
	if !strings.Contains(src, "func (*Only) isSingleton() {}") {
		t.Errorf("missing single-variant stub; got:\n%s", src)
	}
}
