package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const shapeSrc = `package p

//sumtype:decl
type Shape interface {
	isShape()
}

//gosumtype:impl Shape
type (
	Circle struct {
		Radius float64
	}
	Square struct {
		Side float64
	}
	Triangle struct {
		Base   float64
		Height float64
	}
	Rectangle struct {
		Width  float64
		Height float64
	}
)
`

const shapeWithGenericsSrc = `package p

//sumtype:decl
type Shape interface {
	isShape()
}

//gosumtype:impl Shape
type (
	Circle struct {
		Radius float64
	}
	Square struct {
		Side float64
	}
	Triangle struct {
		Base   float64
		Height float64
	}
	Scaled[N interface{ ~float64 }] struct {
		Inner  Shape
		Factor N
	}
)
`

func TestIntegration_processWritesOutputFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	inputFile := filepath.Join(dir, "shapes.go")
	if err := os.WriteFile(inputFile, []byte(shapeSrc), 0644); err != nil {
		t.Fatalf("write input: %v", err)
	}

	if err := process(inputFile); err != nil {
		t.Fatalf("process: %v", err)
	}

	outputFile := filepath.Join(dir, "shapes_sumtypes.go")
	data, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("read output file: %v", err)
	}

	src := string(data)
	if !strings.HasPrefix(src, "// Code generated by go-sumtype. DO NOT EDIT.") {
		t.Error("output missing do-not-edit header")
	}
	if !strings.Contains(src, "package p") {
		t.Error("output missing package declaration")
	}
	// go/format aligns {} bodies for same-named functions; check signature only.
	for _, want := range []string{
		"func (*Circle) isShape()",
		"func (*Square) isShape()",
		"func (*Triangle) isShape()",
		"func (*Rectangle) isShape()",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("output missing %q\n\nfull output:\n%s", want, src)
		}
	}
}

func TestIntegration_noSumTypeBlocksWritesNoOutputFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	inputFile := filepath.Join(dir, "types.go")
	if err := os.WriteFile(inputFile, []byte(`package p

type (
	Shape  interface{ String() string }
	Circle struct{}
)
`), 0644); err != nil {
		t.Fatalf("write input: %v", err)
	}

	if err := process(inputFile); err != nil {
		t.Fatalf("process: %v", err)
	}

	outputFile := filepath.Join(dir, "types_sumtypes.go")
	if _, err := os.Stat(outputFile); !os.IsNotExist(err) {
		t.Error("expected no output file when no sumtype blocks present")
	}
}

func TestIntegration_genericsInOutputFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	inputFile := filepath.Join(dir, "shapes.go")
	if err := os.WriteFile(inputFile, []byte(shapeWithGenericsSrc), 0644); err != nil {
		t.Fatalf("write input: %v", err)
	}

	if err := process(inputFile); err != nil {
		t.Fatalf("process: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "shapes_sumtypes.go"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	src := string(data)
	if !strings.Contains(src, "func (*Scaled[N]) isShape()") {
		t.Errorf("missing generic stub; got:\n%s", src)
	}
}

func TestIntegration_outputFileNameDerivedFromInput(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	inputFile := filepath.Join(dir, "myfile.go")
	if err := os.WriteFile(inputFile, []byte(shapeSrc), 0644); err != nil {
		t.Fatalf("write input: %v", err)
	}

	if err := process(inputFile); err != nil {
		t.Fatalf("process: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "myfile_sumtypes.go")); err != nil {
		t.Errorf("expected myfile_sumtypes.go to exist: %v", err)
	}
}

func TestIntegration_generatedCodeCompiles(t *testing.T) {
	t.Parallel()
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go binary not in PATH")
	}

	dir := t.TempDir()
	writeFile := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	writeFile("go.mod", "module p\ngo 1.21\n")
	writeFile("shapes.go", shapeSrc)

	if err := process(filepath.Join(dir, "shapes.go")); err != nil {
		t.Fatalf("process: %v", err)
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build failed:\n%s", out)
	}
}

func TestIntegration_generatedGenericCodeCompiles(t *testing.T) {
	t.Parallel()
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go binary not in PATH")
	}

	dir := t.TempDir()
	writeFile := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	writeFile("go.mod", "module p\ngo 1.21\n")
	writeFile("shapes.go", shapeWithGenericsSrc)

	if err := process(filepath.Join(dir, "shapes.go")); err != nil {
		t.Fatalf("process: %v", err)
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build failed:\n%s", out)
	}
}

func TestIntegration_multipleSumTypesCompile(t *testing.T) {
	t.Parallel()
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go binary not in PATH")
	}

	const src = `package p

//sumtype:decl
type Shape interface {
	isShape()
}

//gosumtype:impl Shape
type (
	Circle struct{ Radius float64 }
	Square struct{ Side float64 }
)

//sumtype:decl
type Color interface {
	isColor()
}

//gosumtype:impl Color
type (
	Red   struct{}
	Blue  struct{}
	Green struct{}
)
`

	dir := t.TempDir()
	writeFile := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	writeFile("go.mod", "module p\ngo 1.21\n")
	writeFile("types.go", src)

	if err := process(filepath.Join(dir, "types.go")); err != nil {
		t.Fatalf("process: %v", err)
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build failed:\n%s", out)
	}
}

func TestIntegration_invalidGoReturnsError(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	inputFile := filepath.Join(dir, "bad.go")
	if err := os.WriteFile(inputFile, []byte(`package p
this is not {{{ valid go`), 0644); err != nil {
		t.Fatalf("write input: %v", err)
	}

	if err := process(inputFile); err == nil {
		t.Fatal("expected error for invalid Go, got nil")
	}
}
