// Code generated by go-sumtype. DO NOT EDIT.

package examples

func (*Circle) isShape()    {}
func (*Square) isShape()    {}
func (*Triangle) isShape()  {}
func (*Scaled[N]) isShape() {}

func (*LitExpr) isExpr() {}
func (*AddExpr) isExpr() {}
func (*NegExpr) isExpr() {}
